Repository uos-zetin/linetracer-counter, pull requests merged in 2025-07, with the labels that each got.

#6 서버(백엔드) 초기 설정 및 모델링
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/core/models.ts
  server/src/core/repositories.ts
  server/src/core/services.ts
  server/src/index.ts
  server/src/infrastructure/routes/ping-pong.ts
  server/tsconfig.json
Labels: enhancement

#9 서버 CompetitionService 테스트 코드 작성 및 구현
  server/jest.config.ts
  server/package-lock.json
  server/package.json
  server/src/core/errors.ts
  server/src/core/models.ts
  server/src/core/services.ts
  server/src/repositories/competition-sqlite.ts
  server/src/repositories/division-sqlite.ts
  server/src/services/competition.ts
  server/src/utils/auth.ts
  server/tests/integration/repositories/competition-sqlite.test.ts
  server/tests/integration/repositories/division-sqlite.test.ts
  server/tests/shared/repositories/competition.contract.ts
  server/tests/shared/repositories/division.contract.ts
  server/tests/unit/services/competition.test.ts
  server/tsconfig.json
Labels: enhancement

#15 feat: Division 모델, 레포지토리, 서비스, 테스트에서 stopwatchId 제거 #14
  server/src/core/models.ts
  server/src/core/services.ts
  server/src/repositories/division-sqlite.ts
  server/src/services/competition.ts
  server/tests/shared/repositories/division.contract.ts
  server/tests/unit/services/competition.test.ts
Labels: enhancement

#18 Timer 엔티티 구현
  client/eslint.config.js
  client/package-lock.json
  client/package.json
  client/src/entities/timer/index.ts
  client/src/entities/timer/model/__test__/reducers.test.ts
  client/src/entities/timer/model/__test__/selectors.test.ts
  client/src/entities/timer/model/__test__/store.test.ts
  client/src/entities/timer/model/index.ts
  client/src/entities/timer/model/reducers.ts
  client/src/entities/timer/model/selectors.ts
  client/src/entities/timer/model/slice.zustand.ts
  client/src/entities/timer/model/types.ts
  client/src/entities/timer/ui/__test__/timer-view.test.tsx
  client/src/entities/timer/ui/format-time.ts
  client/src/entities/timer/ui/index.ts
  client/src/entities/timer/ui/timer-view.tsx
  client/src/shared/api/errors.ts
  client/src/shared/api/fetcher.ts
  client/src/shared/api/models.ts
  client/src/shared/hooks/index.ts
  client/test-setup.ts
  client/tsconfig.app.json
  client/vitest.config.ts
Labels: enhancement

#17 feat: 대회 및 부문 관련 컨트롤러, DTO 추가 및 AppModule에 통합
  server/src/http/app.module.ts
  server/src/http/controllers/competition.controller.ts
  server/src/http/controllers/division.controller.ts
  server/src/http/dtos/competition.dto.ts
  server/src/http/dtos/division.dto.ts
Labels: enhancement

#22 FSD에 맞지 않는 구조 변경
  client/src/entities/timer/index.ts
  client/src/entities/timer/model/index.ts
  client/src/entities/timer/model/reducers.ts
  client/src/entities/timer/model/slice.zustand.ts
  client/src/entities/timer/model/types.ts
  client/src/entities/timer/ui/index.ts
  client/src/entities/timer/ui/timer-view.tsx
  client/src/shared/index.ts
Labels: invalid

#25 Participant 서비스 구현 및 컨트롤러 등록
  server/src/container.ts
  server/src/core/services.ts
  server/src/http/app.module.ts
  server/src/http/controllers/division.controller.ts
  server/src/http/controllers/participant.controller.ts
  server/src/http/dtos/participant.dto.ts
  server/src/services/participant.ts
  server/tests/unit/services/participant.test.ts
Labels: enhancement

#27 Stopwatch 엔티티 구현
  client/src/entities/stopwatch/index.ts
  client/src/entities/stopwatch/model/__test__/store.test.ts
  client/src/entities/stopwatch/model/selectors.ts
  client/src/entities/stopwatch/model/slice.zustand.ts
  client/src/entities/stopwatch/model/types.ts
  client/src/entities/stopwatch/ui/format.ts
  client/src/entities/stopwatch/ui/stopwatch-view.tsx
Labels: enhancement

#31 엔티티 모델 타입 및 Public API 지정
  client/src/entities/competition/index.ts
  client/src/entities/competition/model/types.ts
  client/src/entities/division/index.ts
  client/src/entities/division/model/types.ts
  client/src/entities/participant/index.ts
  client/src/entities/participant/model/types.ts
  client/src/entities/record/index.ts
  client/src/entities/record/model/types.ts
Labels: enhancement

#33 Record 서비스 구현 및 컨트롤러 등록
  server/src/container.ts
  server/src/core/services.ts
  server/src/http/app.module.ts
  server/src/http/controllers/division.controller.ts
  server/src/http/controllers/participant.controller.ts
  server/src/http/controllers/record.controller.ts
  server/src/http/dtos/record.dto.ts
  server/src/services/record.ts
  server/tests/unit/services/record.test.ts
Labels: enhancement

#35 Timer 서비스 구현 및 컨트롤러 등록
  server/src/container.ts
  server/src/core/errors.ts
  server/src/core/models.ts
  server/src/core/services.ts
  server/src/http/app.module.ts
  server/src/http/controllers/participant.controller.ts
  server/src/http/dtos/timer-log.dto.ts
  server/src/http/exception.filter.ts
  server/src/services/timer-log.ts
  server/tests/shared/repositories/timer-log.contract.ts
  server/tests/unit/services/timer-log.test.ts
Labels: enhancement

#39 ManualRecord 서비스 추가 및 API 등록
  server/src/container.ts
  server/src/core/models.ts
  server/src/core/services.ts
  server/src/http/app.module.ts
  server/src/http/controllers/participant.controller.ts
  server/src/http/dtos/manual-record.dto.ts
  server/src/repositories/manual-record-sqlite.ts
  server/src/services/manual-record.ts
  server/tests/shared/repositories/manual-record.contract.ts
  server/tests/unit/services/manual-record.test.ts
Labels: enhancement

#45 서비스 레이어와 전반적인 서버 디렉터리 구조 개선
  server/src/container.ts
  server/src/core/interfaces.ts
  server/src/core/services.ts
  server/src/core/services/actor.ts
  server/src/core/services/competition.actor.ts
  server/src/core/services/competition.ts
  server/src/core/services/participant.actor.ts
  server/src/core/services/participant.ts
  server/src/core/utils/auth.ts
  server/src/http/app.module.ts
  server/src/http/controllers/actor.controller.ts
  server/src/http/controllers/competition.controller.ts
  server/src/http/controllers/division.controller.ts
  server/src/http/controllers/participant.controller.ts
  server/src/http/controllers/record.controller.ts
  server/src/http/middlewares/actor-session.middleware.ts
  server/src/infrastructure/repositories/actor-id-pw-sqlite.ts
  server/src/infrastructure/repositories/actor-sqlite.ts
  server/src/infrastructure/repositories/competition-sqlite.ts
  server/src/infrastructure/repositories/division-sqlite.ts
  server/src/infrastructure/repositories/manual-record-sqlite.ts
  server/src/infrastructure/repositories/participant-sqlite.ts
  server/src/infrastructure/repositories/record-sqlite.ts
  server/src/infrastructure/repositories/timer-log-sqlite.ts
  server/src/infrastructure/session/actor-session-random-store.ts
  server/src/services/competition.ts
  server/src/services/manual-record.ts
  server/src/services/participant.ts
  server/src/services/record.ts
  server/src/services/timer-log.ts
  server/tests/integration/repositories/actor-id-pw-sqlite.test.ts
  server/tests/integration/repositories/actor-sqlite.test.ts
  server/tests/integration/repositories/competition-sqlite.test.ts
  server/tests/integration/repositories/division-sqlite.test.ts
  server/tests/integration/repositories/manual-record-sqlite.test.ts
  server/tests/integration/repositories/participant-sqlite.test.ts
  server/tests/integration/repositories/record-sqlite.test.ts
  server/tests/integration/repositories/timer-log-sqlite.test.ts
  server/tests/unit/services/competition.test.ts
  server/tests/unit/services/manual-record.test.ts
  server/tests/unit/services/participant.test.ts
  server/tests/unit/services/record.test.ts
  server/tests/unit/services/timer-log.test.ts
Labels: enhancement

#49 계수기 디바이스 상태 관리 및 서비스, 컨트롤러 레이어 구현
  server/.gitignore
  server/docs/assets/counter-architecture-diagram-dark.png
  server/docs/assets/counter-architecture-diagram-light.png
  server/docs/assets/counter-architecture-diagram.drawio
  server/docs/counter-architecture.md
  server/src/container.ts
  server/src/core/errors.ts
  server/src/core/interfaces.ts
  server/src/core/models.ts
  server/src/core/repositories.ts
  server/src/core/services/counter.actor.ts
  server/src/core/services/counter.ts
  server/src/core/services/division-progress.ts
  server/src/http/app.module.ts
  server/src/http/controllers/counter.controller.ts
  server/src/http/dtos/counter.dto.ts
  server/src/http/exception.filter.ts
  server/src/http/gateway/counter.gateway.ts
  server/src/infrastructure/counters/counter-device-manager.actor.ts
  server/src/infrastructure/counters/counter-device-manager.ts
  server/src/infrastructure/counters/front-back-ir-counter-device.ts
  server/tests/unit/counters/front-back-ir-counter-device.test.ts
  server/tests/unit/services/counter.test.ts
  server/tests/unit/services/division-progress.test.ts
  server/tsconfig.json
Labels: enhancement

#53 계수기 시뮬레이터 추가 및 관리자 계정 생성 스크립트 입력 개선
  server/package-lock.json
  server/package.json
  server/src/scripts/create-admin.ts
  server/src/scripts/simulate-counter.ts
Labels: enhancement

#58 RESTful API 설계 적용 및 Swagger 개선
  server/src/core/models.ts
  server/src/core/services/competition.actor.ts
  server/src/core/services/counter.ts
  server/src/http/controllers/actor.controller.ts
  server/src/http/controllers/competition.controller.ts
  server/src/http/controllers/counter.controller.ts
  server/src/http/controllers/division.controller.ts
  server/src/http/controllers/participant.controller.ts
  server/src/http/controllers/record.controller.ts
  server/src/http/dtos/counter.dto.ts
  server/src/http/dtos/division.dto.ts
Labels: enhancement

#65 fix: CounterService 단위 테스트 실패 해결(id 필드를 deviceId 필드로 변경)
  server/tests/unit/services/counter.test.ts
Labels: bug

#66 온프레미스 서버 배포 스크립트 작성
  .dockerignore
  deployment/zetin-server/Dockerfile
  deployment/zetin-server/deploy
  deployment/zetin-server/docker-compose.yaml
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/scripts/create-admin.ts
  server/scripts/simulate-counter.ts
  server/src/env.ts
  server/src/http/app.module.ts
  server/src/http/bootstrap.ts
Labels: enhancement

#73 빌드 오류 해결
  client/eslint.config.js
  client/src/entities/competition/api/__test__/repository.test.ts
  client/src/entities/counter/api/__test__/repository.test.ts
  client/src/entities/division/api/__test__/repository.test.ts
  client/src/entities/manual-record/api/__test__/repository.test.ts
  client/src/entities/participant/api/__test__/repository.test.ts
  client/src/entities/record/api/__test__/repository.test.ts
  client/src/entities/timer/api/__test__/repository.test.ts
  client/src/entities/timer/api/repository.ts
  client/src/entities/user/api/__test__/repository.test.ts
  client/src/features/auth/index.ts
  client/src/features/auth/lib/__test__/validation.test.ts
  client/src/features/auth/lib/validation.ts
  client/src/features/auth/model/__test__/auth-service.test.ts
  client/src/features/auth/model/__test__/store.zustand.test.ts
  client/src/features/auth/model/auth-service.ts
  client/src/features/progress/api/__test__/repository.test.ts
  client/src/features/progress/api/repository.mock.ts
  client/src/features/progress/model/__test__/store.zustand.test.ts
  client/src/pages/timer/ui.tsx
  server/src/http/app.module.ts
Labels: bug, enhancement

#76 소켓 관련 리팩토링 및 문서 추가
  server/docs/socket-event.md
  server/src/http/app.module.ts
  server/src/http/gateways/counter.gateway.ts
  server/src/http/gateways/division-progress.gateway.ts
Labels: documentation, enhancement
