Repository uos-zetin/linetracer-counter, pull requests merged in 2025-08, with the labels that each got.

#90 타이머 페이지에 Progress 구독 추가
  client/src/pages/timer/ui.tsx
  client/src/pages/timer/ui/current-record-view.tsx
  client/src/pages/timer/ui/division-info.tsx
  client/src/pages/timer/ui/next-runner-info.tsx
  client/src/pages/timer/ui/runner-info.tsx
  client/src/pages/timer/ui/stopwatch-view.tsx
  client/src/pages/timer/ui/timer-header.tsx
  client/src/pages/timer/ui/top-record-info.tsx
Labels: enhancement

#105 디자인 시스템 추가
  client/package-lock.json
  client/package.json
  client/src/shared/ui/alert.tsx
  client/src/shared/ui/badge.tsx
  client/src/shared/ui/button.tsx
  client/src/shared/ui/card.tsx
  client/src/shared/ui/dialog.tsx
  client/src/shared/ui/index.ts
  client/src/shared/ui/input.tsx
  client/src/shared/ui/select.tsx
  client/src/shared/ui/sonner.tsx
  client/src/shared/ui/table.tsx
  client/src/shared/ui/textarea.tsx
Labels: enhancement

#109 Shared & Entity Layer 리팩토링
  client/src/app/providers/fetcher-provider.tsx
  client/src/app/providers/use-fetcher.ts
  client/src/entities/competition/api/__test__/repository.test.ts
  client/src/entities/competition/api/repository.ts
  client/src/entities/competition/lib/parse-dto.ts
  client/src/entities/competition/model/store.zustand.ts
  client/src/entities/competition/model/types.ts
  client/src/entities/competition/model/validation.ts
  client/src/entities/counter/api/__test__/repository.test.ts
  client/src/entities/counter/api/repository.ts
  client/src/entities/counter/model/__test__/store.zustand.test.ts
  client/src/entities/counter/model/store.zustand.ts
  client/src/entities/counter/model/types.ts
  client/src/entities/division/api/__test__/repository.test.ts
  client/src/entities/division/api/repository.ts
  client/src/entities/division/api/types.ts
  client/src/entities/division/lib/parse-dto.ts
  client/src/entities/division/model/store.zustand.ts
  client/src/entities/division/model/types.ts
  client/src/entities/division/model/validation.ts
  client/src/entities/manual-record/api/repository.ts
  client/src/entities/manual-record/lib/parse-dto.ts
  client/src/entities/manual-record/model/types.ts
  client/src/entities/manual-record/model/validation.ts
  client/src/entities/participant/api/repository.ts
  client/src/entities/participant/lib/parse-dto.ts
  client/src/entities/participant/model/store.zustand.ts
  client/src/entities/participant/model/types.ts
  client/src/entities/participant/model/validation.ts
  client/src/entities/record/api/repository.ts
  client/src/entities/record/lib/parse-dto.ts
  client/src/entities/record/model/store.zustand.ts
  client/src/entities/record/model/types.ts
  client/src/entities/record/model/validation.ts
  client/src/entities/timer/model/types.ts
  client/src/entities/user/api/repository.ts
  client/src/entities/user/api/types.ts
  client/src/entities/user/lib/parse-dto.ts
  client/src/entities/user/model/store.zustand.ts
  client/src/entities/user/model/types.ts
  client/src/entities/user/model/validation.ts
  client/src/features/counter/model/service.ts
  client/src/shared/api/errors.ts
  client/src/shared/api/fetcher.authenticated.ts
  client/src/shared/api/fetcher.fetch.ts
  client/src/shared/api/index.ts
  client/src/shared/api/types.ts
  client/src/shared/config/index.ts
  client/src/shared/lib/entity-store.ts
  client/src/shared/lib/index.ts
  client/src/shared/lib/sort-utils.ts
  client/src/shared/types/index.ts
Labels: enhancement

#114 Raspberry Pi 센서 데이터 전송 시스템 서비스 구현
  counters/rpi-counter-sensor/.gitignore
  counters/rpi-counter-sensor/CMakeLists.txt
  counters/rpi-counter-sensor/README.md
  counters/rpi-counter-sensor/config.example.json
  counters/rpi-counter-sensor/rpi-counter-sensor.service
  counters/rpi-counter-sensor/src/bpw34_sensor_data_reader.cpp
  counters/rpi-counter-sensor/src/bpw34_sensor_data_reader.hpp
  counters/rpi-counter-sensor/src/config.cpp
  counters/rpi-counter-sensor/src/config.hpp
  counters/rpi-counter-sensor/src/http_curl_client.cpp
  counters/rpi-counter-sensor/src/http_curl_client.hpp
  counters/rpi-counter-sensor/src/http_sensor_data_sender.cpp
  counters/rpi-counter-sensor/src/http_sensor_data_sender.hpp
  counters/rpi-counter-sensor/src/interfaces.hpp
  counters/rpi-counter-sensor/src/logger.cpp
  counters/rpi-counter-sensor/src/logger.hpp
  counters/rpi-counter-sensor/src/main.cpp
  counters/rpi-counter-sensor/src/thread_safe_queue.hpp
Labels: enhancement

#118 계수기 관련 펌웨어 및 서버측 개선 작업
  counters/rpi-counter-sensor/src/bpw34_sensor_data_reader.cpp
  counters/rpi-counter-sensor/src/http_curl_client.cpp
  counters/rpi-counter-sensor/src/http_curl_client.hpp
  counters/rpi-counter-sensor/src/http_sensor_data_sender.cpp
  server/src/infrastructure/counters/front-back-ir-counter-device.ts
  server/tests/unit/counters/front-back-ir-counter-device.test.ts
Labels: bug, enhancement

#127 무한 fetch 문제 수정
  client/src/features/competition/model/service.ts
  client/src/features/counter/model/service.ts
  client/src/features/counter/model/types.ts
  client/src/features/division/model/service.ts
  client/src/features/division/ui/admin-division-edit-modal.tsx
  client/src/features/participant/model/service.ts
  client/src/features/record/model/service.ts
  client/src/features/user/model/service.ts
  client/src/pages/admin/ui/participant-management.tsx
  client/src/pages/admin/ui/record-management.tsx
  client/src/pages/admin/ui/user-management.tsx
  client/src/pages/controller/ui/counter-control-section.tsx
  client/src/pages/controller/ui/progress-monitor-section.tsx
  client/src/pages/counter-selector/ui/counter-selector-page.tsx
  client/src/pages/dashboard/ui/dashboard-page.tsx
  client/src/pages/manual-counter/ui/manual-counter-page.tsx
Labels: bug

#129 User repository api 경로 오류 수정
  client/src/entities/user/api/repository.ts
Labels: bug

#130 Admin 페이지 오류 수정
  client/src/pages/admin/ui/participant-management.tsx
  client/src/pages/admin/ui/record-management.tsx
Labels: bug

#135 Timer 단위 변경
  client/src/entities/timer/ui/formatters.ts
  client/src/features/record/ui/record-list-display.tsx
  client/src/features/timer-control/index.ts
  client/src/features/timer-control/ui/timer-adjust-controls.tsx
  client/src/features/timer-control/ui/timer-display.tsx
  client/src/features/timer-control/ui/timer-start-button.tsx
  client/src/features/timer-control/ui/timer-stop-button.tsx
  client/src/pages/admin/ui/record-management.tsx
  client/src/pages/controller/ui/current-records-list.tsx
  client/src/pages/controller/ui/timer-runner-control-section.tsx
  client/src/pages/timer/ui/timer-view.tsx
Labels: enhancement

#140 CSV 파일로 대회 생성하는 기능 추가
  client/package-lock.json
  client/package.json
  client/src/app/providers/app-providers.tsx
  client/src/app/providers/csv-provider.tsx
  client/src/entities/participant/api/repository.ts
  client/src/entities/participant/api/types.ts
  client/src/entities/user/api/__test__/repository.test.ts
  client/src/features/csv-to-competition/index.ts
  client/src/features/csv-to-competition/lib/parse-csv.ts
  client/src/features/csv-to-competition/lib/retry-utils.ts
  client/src/features/csv-to-competition/model/context.ts
  client/src/features/csv-to-competition/model/service.ts
  client/src/features/csv-to-competition/model/types.ts
  client/src/features/csv-to-competition/ui/csv-import-modal.tsx
  client/src/pages/admin/ui/competition-management.tsx
Labels: enhancement

#143 계수기 전송 로그 개선 및 에러 핸들링 책임 전가
  counters/rpi-counter-sensor/src/http_sensor_data_sender.cpp
  counters/rpi-counter-sensor/src/main.cpp
Labels: enhancement

#148 계수기 Timeout 설정 가능하게 변경 및 HTTP Keep-Alive 적용
  counters/rpi-counter-sensor/config.example.json
  counters/rpi-counter-sensor/src/config.cpp
  counters/rpi-counter-sensor/src/config.hpp
  counters/rpi-counter-sensor/src/http_curl_client.cpp
  counters/rpi-counter-sensor/src/http_curl_client.hpp
  counters/rpi-counter-sensor/src/http_sensor_data_sender.cpp
  counters/rpi-counter-sensor/src/http_sensor_data_sender.hpp
  counters/rpi-counter-sensor/src/main.cpp
Labels: enhancement

#152 Favicon 추가
  client/index.html
  client/public/android-chrome-192x192.png
  client/public/android-chrome-512x512.png
  client/public/apple-touch-icon.png
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
Labels: enhancement

#156 특정 참가자의 수동 계수 기록 리셋 기능 추가
  server/src/core/services/participant.actor.ts
  server/src/core/services/participant.ts
  server/src/http/controllers/participant.controller.ts
  server/tests/unit/services/participant.test.ts
Labels: enhancement

#159 Timer 페이지 UI 수정
  client/package-lock.json
  client/package.json
  client/src/pages/timer/ui/current-record-view.tsx
  client/src/pages/timer/ui/division-info.tsx
  client/src/pages/timer/ui/next-runner-info.tsx
  client/src/pages/timer/ui/qr-viewer.tsx
  client/src/pages/timer/ui/runner-info.tsx
  client/src/pages/timer/ui/timer-header.tsx
  client/src/pages/timer/ui/timer-page.tsx
  client/src/pages/timer/ui/top-record-info.tsx
Labels: bug, enhancement
